# Use official Node.js base image
FROM node:18-alpine

# Set working directory
WORKDIR /index.js

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the backend code
COPY . .

# Expose the backend port
EXPOSE 5000

# Run the application
CMD ["npm", "start"]
