name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u dps9760 "${{ secrets.DOCKERHUB_USERNAME }}" --password- Dharm@9760
    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend ./frontend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend

    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend ./backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend

    - name: Deploy to Frontend Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FRONTEND_SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend
          docker stop frontend || true && docker rm frontend || true
          docker run -d --name frontend -p 3000:80 ${{ secrets.DOCKERHUB_USERNAME }}/frontend

    - name: Deploy to Backend Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BACKEND_SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend
          docker stop backend || true && docker rm backend || true
          docker run -d --name backend -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/backend
